ログイン画面作成
YukiNukui/chat_tool pull request #14
Opened 2022-08-13 15:36 UTC by YukiNukui

ログイン画面の見た目を作成しました。

slackで相談させていただいた通り、
フォントファミリーの設定がうまくいかず、XDファイルと相違があります。
→font size、widthにて調整しています。（Login.css にコメント記載）

![image](https://user-images.githubusercontent.com/102654819/184500873-75da9270-725a-4faf-bdf1-0455f69280b6.png)

2022-08-13 16:42 UTC, shunya-tanaka-512 requested changes

2022-08-13 16:42 UTC, shunya-tanaka-512 commented on react_chat_tool/src/App.tsx
> +          <input type="submit" value="ログイン" className="Login-button" />
今はinput submitって使わないですね。
buttonタグが主流です。

2022-08-13 16:42 UTC, shunya-tanaka-512 commented on react_chat_tool/src/App.tsx
> +          <input type="password" name="pass" placeholder="パスワード" className="Input-box"/>
せっかくreact使ってるので

https://mui.com/material-ui/react-text-field/

のようなコンポーネントを使ってみましょう

2022-08-17 08:47 UTC, YukiNukui commented on react_chat_tool/src/App.tsx
> +          <input type="submit" value="ログイン" className="Login-button" />
修正いたしました。

2022-08-17 08:49 UTC, YukiNukui commented on react_chat_tool/src/App.tsx
> +          <input type="password" name="pass" placeholder="パスワード" className="Input-box"/>
slackでのお話の通り、今回は対象外とします。

2022-08-17 10:10 UTC, shunya-tanaka-512 approved these changes

2022-08-19 10:12 UTC, merged