新規登録画面
YukiNukui/chat_tool pull request #15
Opened 2022-08-20 07:35 UTC by YukiNukui

新規登録画面を作成しました。
ご確認お願いします。

・ログイン画面と同様に、フォントがXDファイル通りではない箇所があります。
・水平線ですが、ログイン画面と同様にファイルからわからなかったので、
　展開いただいていたログイン画面の座標と同じで設計しました。
・リンクのためにApp.tsx内のコンポーネントを分けました。
　（差分が多く出ると思って今回は避けたのですが、
　　後からログイン画面のコンポーネントを別ファイルに分けようと思います。）

![image](https://user-images.githubusercontent.com/102654819/185734197-baff094c-a70b-427f-8ed1-21ee1e38a8ef.png)

2022-08-20 12:09 UTC, shunya-tanaka-512 requested changes
ログインも新規登録も文言が少し違うだけでほぼ同じ画面なのでコンポーネント化して再利用してほしいです。

2022-08-24 06:08 UTC, YukiNukui commented
コンポーネント再利用に対応しました。

2022-08-24 08:04 UTC, YukiNukui commented
スクショを添付します。
▼ログイン画面
<img width="748" alt="スクリーンショット 2022-08-24 17 02 29" src="https://user-images.githubusercontent.com/102654819/186364509-a6ddc149-de71-45ea-8c88-ef0711c65d7d.png">
▼新規登録画面
<img width="748" alt="スクリーンショット 2022-08-24 17 02 36" src="https://user-images.githubusercontent.com/102654819/186364539-8c46afad-13fe-48f6-b7bf-b0075359ed5c.png">

2022-08-24 08:12 UTC, shunya-tanaka-512 approved these changes
ばっちりです

2022-08-24 08:44 UTC, merged