React環境構築
YukiNukui/chat_tool pull request #5
Opened 2022-07-18 09:20 UTC by YukiNukui

Issues #1 React初期化 を実施しました。
ご確認お願いします。

2022-07-18 09:26 UTC, shunya-tanaka-512 requested changes
.ds_storeファイルはgitignoreにしましょう

2022-07-18 09:29 UTC, shunya-tanaka-512 requested changes

2022-07-18 09:29 UTC, shunya-tanaka-512 commented on react_chat_tool/Dockerfile
> +WORKDIR /usr/src/app
これだけじゃdockerでこのプロジェクト動かないです。
docker runで動かした時にこのプロジェクトが実行されるようにしましょう

2022-07-18 13:42 UTC, YukiNukui commented on react_chat_tool/Dockerfile
> +WORKDIR /usr/src/app
<img width="604" alt="スクリーンショット 2022-07-18 22 31 28" src="https://user-images.githubusercontent.com/102654819/179524239-2a495090-c86f-443a-8e50-1ef878bddc0f.png">

・dockerファイルを修正しました。

・.DS_Store　を　.gitignore　に記載しました。

2022-07-19 01:09 UTC, shunya-tanaka-512 commented
@YukiNukui 
.DS_Storeがファイルとして既に上がっているので削除してください

2022-07-19 01:22 UTC, shunya-tanaka-512 reviewed
ひとつ完全に忘れてました。
Reactの初期化コマンドとして、
`npx create-react-app --template typescript {project_name}`
のようにTypescriptを指定する必要がありました。
こうしないとデフォルトはJavascriptなので。
割と大きく作り直しなのでブランチ作り直してもいいです。
あとブランチ名がfeatureだと何してるブランチなのかわからないので、
ブランチ名は作業内容の概要がわかるような名前にしましょう。

2022-07-19 01:22 UTC, shunya-tanaka-512 commented on react_chat_tool/Dockerfile
> +COPY . /usr/src/app
二回に分けてコピーする必要ないです。
まるっとコピーすればいい。
でもnode_modulesフォルダはコピーしたくないので、
以下を参考にコピーしないようにしてください。
https://www.mitomex.blog/docker-dockerignore/

2022-07-21 00:59 UTC, shunya-tanaka-512 approved these changes
docker run -d -p 3000:3000 react_chat
で起動することを確認しました

2022-07-21 13:27 UTC, merged