Compose init
YukiNukui/chat_tool pull request #9
Opened 2022-08-03 14:35 UTC by YukiNukui

docker-compose.ymlを追加
▼react起動
<img width="598" alt="スクリーンショット 2022-08-03 23 12 33" src="https://user-images.githubusercontent.com/102654819/182635197-d97627f3-18ac-47b9-8fbd-a15e80bcf623.png">
▼flask起動
<img width="506" alt="スクリーンショット 2022-08-03 23 12 20" src="https://user-images.githubusercontent.com/102654819/182635228-eb66168e-62d7-4ae3-b086-ab34a37d097d.png">
▼MySQL起動
<img width="598" alt="スクリーンショット 2022-08-03 23 14 06" src="https://user-images.githubusercontent.com/102654819/182635257-1a2eba35-0fcf-469e-b3a0-f3a9db938ff8.png">
▼マウント反映確認
<img width="930" alt="スクリーンショット 2022-08-03 23 30 14" src="https://user-images.githubusercontent.com/102654819/182635316-4bd125b0-67c9-420a-ad6c-a36732ef3632.png">

2022-08-03 15:06 UTC, shunya-tanaka-512 submitted a review, later dismissed

2022-08-07 08:12 UTC, shunya-tanaka-512 requested changes

2022-08-07 08:12 UTC, shunya-tanaka-512 commented on docker-compose.yml
> +      - ./react_chat_tool/src:/usr/src/app
階層ひとつ変わってませんか？
元々react_chat_tool直下がコピーされていたはず

2022-08-07 09:00 UTC, YukiNukui commented on docker-compose.yml
> +      - ./react_chat_tool/src:/usr/src/app
パス修正しました。
ご確認お願いします。

<img width="763" alt="スクリーンショット 2022-08-07 17 35 08" src="https://user-images.githubusercontent.com/102654819/183283410-62ce7251-21cd-47e2-b575-5afe25095439.png">

2022-08-07 09:06 UTC, shunya-tanaka-512 approved these changes

2022-08-07 09:15 UTC, merged